only_rules:
  - closure_spacing
  - colon
  - empty_enum_arguments
  - force_cast
#  - fatal_error_message
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

excluded:
  - Carthage
  - Pods
  - tools
  - third-party

colon:
  apply_to_dictionaries: false

indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error

identifier_name:
  excluded:
    - id
    - C
    - x
    - y
    - M
    - Id

type_name:
  max_length: # warning and error
    warning: 140
    error: 150
  excluded:
  - C
  - M
  - Id
